//! Genesis block creation for Tenzro Network testnet
//!
//! Handles initial chain state: pre-funded accounts, validator set,
//! and the genesis block at height 0.

use crate::config::GenesisConfig;
use crate::error::{NodeError, Result};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::sync::Arc;
use tenzro_crypto::{KeyPair, KeyType};
use tenzro_storage::{
    account_store::AccountStoreImpl, block_store::BlockStoreImpl, traits::AccountStore,
    traits::BlockStore, KvStore, RocksDbStore, WriteOp, CF_ACCOUNTS, CF_METADATA, CF_STATE,
};
use tenzro_types::{
    block::{Block, BlockHeader, BlockMetadata, ConsensusAlgorithm, ConsensusProof},
    primitives::{Address, BlockHeight, Hash, Nonce, Timestamp},
    Account, AccountState,
};
use tracing::{info, warn};

/// ERC-8004 predeploy bundle, baked into the binary at compile time.
///
/// Generated by `tools/predeploys/regenerate.sh`, which spins up a local
/// Anvil node, runs the vendored canonical CREATE2 deploy + UUPS upgrade flow
/// from `vendor/erc8004-evm/` against it, snapshots the resulting state via
/// `anvil_dumpState`, and filters to the 8 addresses Tenzro pre-deploys at
/// block 0: SAFE Singleton Factory + MinimalUUPS + 3 vanity proxies + 3
/// implementation contracts. Schema: `tenzro/erc8004-predeploys/v1`.
///
/// Re-run the regenerate script after bumping the vendor pin to refresh.
const ERC8004_PREDEPLOYS_JSON: &str =
    include_str!("../res/genesis/erc8004-predeploys.json");

/// Schema string the loader refuses to deserialize anything else under.
const ERC8004_PREDEPLOYS_SCHEMA: &str = "tenzro/erc8004-predeploys/v1";

/// Metadata key for the faucet's Ed25519 private key (hex, no 0x prefix).
///
/// Stored under CF_METADATA and loaded by the RPC faucet handler so it can
/// sign real transactions instead of bypassing consensus with a direct
/// `token.transfer()` call. Provisioning happens once at first boot via
/// `provision_faucet_signing_key()`.
pub const FAUCET_SIGNING_KEY_PRIVATE: &[u8] = b"faucet_signing_key_private";
/// Metadata key for the faucet's 32-byte address (hex, no 0x prefix).
pub const FAUCET_SIGNING_KEY_ADDRESS: &[u8] = b"faucet_signing_key_address";
/// Metadata key for the faucet's Ed25519 public key bytes (hex, no 0x prefix).
pub const FAUCET_SIGNING_KEY_PUBLIC: &[u8] = b"faucet_signing_key_public";
/// Metadata key for the faucet's ML-DSA-65 seed (32 bytes, hex, no 0x prefix).
///
/// Under the hybrid PQ migration, every signed transaction must carry an
/// ML-DSA-65 verifying key alongside the classical Ed25519 leg. The seed is
/// persisted (rather than the expanded private key) so we can rederive the
/// `MlDsaSigningKey` deterministically across reboots.
pub const FAUCET_PQ_SIGNING_SEED: &[u8] = b"faucet_pq_signing_seed";
/// Metadata key for the faucet's ML-DSA-65 verifying key (1952 bytes, hex).
pub const FAUCET_PQ_VERIFYING_KEY: &[u8] = b"faucet_pq_verifying_key";

/// Environment variable holding the operator's faucet grant, in whole TNZO.
pub const FAUCET_GRANT_ENV: &str = "TENZRO_FAUCET_DISPENSE_AMOUNT";
/// Smallest grant a request may hand out, in whole TNZO.
pub const FAUCET_MIN_GRANT_TNZO: u128 = 100;
/// Largest grant a request may hand out, in whole TNZO.
///
/// A testnet faucet exists to get a new participant to their first real
/// action — a provider posting the 1,000 TNZO admission bond is the largest
/// of those — not to hand out a balance worth farming.
pub const FAUCET_MAX_GRANT_TNZO: u128 = 1_000;

/// Resolve how much TNZO one faucet request hands out, in whole TNZO.
///
/// `genesis.faucet.amount_per_request` is hashed into the genesis state root,
/// so it is frozen for the life of the chain — editing it makes every
/// validator refuse to start on the chain-compatibility check. How much the
/// operator actually hands out is not chain state, so it is read from the
/// environment, falling back to the committed value. Either way the result is
/// clamped to `[FAUCET_MIN_GRANT_TNZO, FAUCET_MAX_GRANT_TNZO]`.
pub fn resolve_faucet_grant_tnzo(genesis_committed: u128) -> u128 {
    let requested = match std::env::var(FAUCET_GRANT_ENV) {
        Ok(raw) => match raw.trim().parse::<u128>() {
            Ok(parsed) => parsed,
            Err(e) => {
                warn!(
                    "{}={:?} is not a whole number of TNZO ({}); using the \
                     genesis-committed {} TNZO instead",
                    FAUCET_GRANT_ENV, raw, e, genesis_committed
                );
                genesis_committed
            }
        },
        Err(_) => genesis_committed,
    };
    let granted = requested.clamp(FAUCET_MIN_GRANT_TNZO, FAUCET_MAX_GRANT_TNZO);
    if granted != requested {
        warn!(
            "Faucet grant of {} TNZO is outside the permitted {}–{} TNZO range; \
             dispensing {} TNZO",
            requested, FAUCET_MIN_GRANT_TNZO, FAUCET_MAX_GRANT_TNZO, granted
        );
    }
    granted
}

/// Genesis protocol version for the PQ-hybrid era.
///
/// Under the hybrid PQ migration, every signed transaction carries a mandatory
/// ML-DSA-65 leg alongside the classical Ed25519 signature. Genesis blocks
/// produced by this binary stamp `protocol_version = 2`. A binary that loads
/// a `protocol_version = 1` genesis from storage refuses to start — the older
/// classical-only wire format is not deserializable here, and silently
/// accepting it would mask the incompatibility.
pub const PQ_HYBRID_PROTOCOL_VERSION: u32 = 2;

/// ERC-8004 predeploy bundle (deserialized from `ERC8004_PREDEPLOYS_JSON`).
///
/// `addresses` is a label→hex-address index of the 8 system contracts;
/// `accounts` is the actual on-chain state to install, keyed by the same
/// hex addresses. We use `BTreeMap` so iteration order is deterministic —
/// every validator computes the same genesis state root.
#[derive(Debug, Deserialize)]
struct Erc8004Bundle {
    schema: String,
    source_commit: String,
    addresses: BTreeMap<String, String>,
    accounts: BTreeMap<String, PredeployAccount>,
}

#[derive(Debug, Deserialize)]
struct PredeployAccount {
    nonce: u64,
    /// `"0x<hex>"`, parsed to `u128`. ERC-8004 predeploys all have balance 0,
    /// but the field is honoured so the bundle schema can carry funded
    /// predeploys in future.
    balance: String,
    /// `"0x<hex>"`, raw contract bytecode (not RLP-wrapped, no length prefix).
    code: String,
    /// Slot key (`"0x<32-byte hex>"`) → slot value (`"0x<32-byte hex>"`).
    storage: BTreeMap<String, String>,
}

/// Parse `"0x<hex>"` (or bare `<hex>`) → owned `Vec<u8>`.
fn parse_hex_bytes(s: &str, what: &str) -> Result<Vec<u8>> {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    hex::decode(stripped).map_err(|e| {
        NodeError::Config(format!("Invalid {} hex {:?}: {}", what, s, e))
    })
}

/// Parse `"0x<hex>"` into a u128, treating empty/`"0x0"` as zero.
fn parse_hex_u128(s: &str, what: &str) -> Result<u128> {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    if stripped.is_empty() {
        return Ok(0);
    }
    u128::from_str_radix(stripped, 16).map_err(|e| {
        NodeError::Config(format!("Invalid {} hex u128 {:?}: {}", what, s, e))
    })
}

/// Right-pad a raw EVM address (20 bytes) to Tenzro's 32-byte address layout
/// by appending 12 zero bytes. This matches `tnzo_balance_key()` in
/// `tenzro_vm::state_adapter` — the canonical CF_ACCOUNTS key for native
/// TNZO balances — so a balance written here is readable by
/// `eth_getBalance`, `tenzro_getBalance`, and revm's `Database::basic()`
/// without any further translation.
fn evm_address_to_tnzo32(evm_addr: &[u8]) -> Result<[u8; 32]> {
    if evm_addr.len() != 20 {
        return Err(NodeError::Config(format!(
            "Expected 20-byte EVM address, got {} bytes",
            evm_addr.len()
        )));
    }
    let mut padded = [0u8; 32];
    padded[..20].copy_from_slice(evm_addr);
    Ok(padded)
}

/// Install the ERC-8004 predeploy bundle into genesis state.
///
/// For each predeploy account, this writes:
/// - `CF_STATE` `code:<40-hex-evm-addr>`     → raw bytecode bytes
/// - `CF_STATE` `nonce:<40-hex-evm-addr>`    → u64 LE (only if `nonce > 0`)
/// - `CF_STATE` `storage:<40-hex>:<64-hex>`  → raw 32-byte slot value
/// - `CF_ACCOUNTS` `balance:<32-byte-padded>` → u128 LE (only if `balance > 0`),
///   mirrored under `CF_STATE` `balance:<64-hex>` for legacy readers
///
/// The key formats are byte-identical to those emitted by
/// `tenzro_vm::state_adapter::StateAdapter::commit()` (and read by
/// `get_code` / `get_storage` / `get_nonce` / `get_balance`), so revm sees
/// these accounts as if they had been deployed by a transaction.
///
/// Returns the SHA-256 commitment of the bundle (incorporated into the
/// genesis state root so validators must agree on the exact predeploy set).
fn install_erc8004_predeploys(
    state_entries: &mut Vec<(Vec<u8>, Vec<u8>)>,
    token_entries: &mut Vec<WriteOp>,
    total_supply: &mut u128,
) -> Result<Hash> {
    let bundle: Erc8004Bundle = serde_json::from_str(ERC8004_PREDEPLOYS_JSON)
        .map_err(|e| NodeError::Config(format!(
            "Failed to parse erc8004-predeploys.json: {}",
            e
        )))?;

    if bundle.schema != ERC8004_PREDEPLOYS_SCHEMA {
        return Err(NodeError::Config(format!(
            "ERC-8004 predeploy bundle schema mismatch: expected {:?}, got {:?}",
            ERC8004_PREDEPLOYS_SCHEMA, bundle.schema
        )));
    }

    // Cross-check the `addresses` label index against the `accounts` keyspace.
    // The regenerate.sh extractor pairs every label (safeSingletonFactory,
    // minimalUUPS, identityProxy/reputationProxy/validationProxy, identityImpl/
    // reputationImpl/validationImpl) with exactly one account entry — a missing
    // pair means the bundle is corrupt and we refuse to come up rather than
    // silently boot a partially-deployed registry. Comparison is case-
    // insensitive since the bundle uses mixed-case checksummed addresses while
    // `accounts` keys preserve the source casing.
    use std::collections::BTreeSet;
    let account_addrs_lower: BTreeSet<String> = bundle
        .accounts
        .keys()
        .map(|s| s.to_ascii_lowercase())
        .collect();
    for (label, declared_addr) in &bundle.addresses {
        let declared_lower = declared_addr.to_ascii_lowercase();
        if !account_addrs_lower.contains(&declared_lower) {
            return Err(NodeError::Config(format!(
                "ERC-8004 predeploy bundle declares address {} ({}) but no \
                 matching account entry exists — bundle is incoherent",
                declared_addr, label
            )));
        }
    }
    if bundle.addresses.len() != bundle.accounts.len() {
        return Err(NodeError::Config(format!(
            "ERC-8004 predeploy bundle has {} declared addresses but {} \
             account entries — counts must match",
            bundle.addresses.len(),
            bundle.accounts.len()
        )));
    }

    // Commitment is bound to the exact JSON bytes — any drift in the bundle
    // (whether content or whitespace) produces a different genesis root.
    let bundle_commitment = compute_erc8004_bundle_commitment();

    let mut code_count = 0usize;
    let mut storage_slot_count = 0usize;
    let mut funded_count = 0usize;

    for (addr_hex, account) in &bundle.accounts {
        let evm_addr = parse_hex_bytes(addr_hex, "predeploy address")?;
        if evm_addr.len() != 20 {
            return Err(NodeError::Config(format!(
                "ERC-8004 predeploy address {} is {} bytes (expected 20)",
                addr_hex, evm_addr.len()
            )));
        }
        // Hex-lowercase the 20-byte address — matches `hex::encode(addr)`
        // in `StateAdapter` getters, which are the readers we must agree with.
        let addr_hex_lower = hex::encode(&evm_addr);

        // --- Code ---
        let code_bytes = parse_hex_bytes(&account.code, "predeploy code")?;
        if code_bytes.is_empty() {
            return Err(NodeError::Config(format!(
                "ERC-8004 predeploy {} has empty code — bundle is corrupt",
                addr_hex
            )));
        }
        let code_key = format!("code:{}", addr_hex_lower);
        state_entries.push((code_key.into_bytes(), code_bytes));
        code_count += 1;

        // --- Nonce (only write if non-zero; absent key reads as 0) ---
        if account.nonce > 0 {
            let nonce_key = format!("nonce:{}", addr_hex_lower);
            state_entries.push((nonce_key.into_bytes(), account.nonce.to_le_bytes().to_vec()));
        }

        // --- Storage slots ---
        for (slot_key_hex, slot_value_hex) in &account.storage {
            let slot_key = parse_hex_bytes(slot_key_hex, "storage slot key")?;
            let slot_value = parse_hex_bytes(slot_value_hex, "storage slot value")?;
            if slot_key.len() != 32 {
                return Err(NodeError::Config(format!(
                    "Storage slot key {} is {} bytes (expected 32)",
                    slot_key_hex, slot_key.len()
                )));
            }
            // Storage key format mirrors `StateAdapter::get_storage`:
            // `storage:<40-hex-addr>:<64-hex-slot-key>`. Value is the raw
            // 32-byte slot contents.
            let db_key = format!(
                "storage:{}:{}",
                addr_hex_lower,
                hex::encode(&slot_key)
            );
            state_entries.push((db_key.into_bytes(), slot_value));
            storage_slot_count += 1;
        }

        // --- Balance (only write if non-zero) ---
        let balance = parse_hex_u128(&account.balance, "predeploy balance")?;
        if balance > 0 {
            let padded = evm_address_to_tnzo32(&evm_addr)?;
            // Canonical: CF_ACCOUNTS under tnzo_balance_key layout.
            let mut token_key = b"balance:".to_vec();
            token_key.extend_from_slice(&padded);
            token_entries.push(WriteOp::Put {
                cf: CF_ACCOUNTS.to_string(),
                key: token_key,
                value: balance.to_le_bytes().to_vec(),
            });
            // Mirror: CF_STATE legacy key (hex-encoded 32-byte addr) so any
            // legacy reader still sees the same balance.
            let legacy_key = format!("balance:{}", hex::encode(padded));
            state_entries.push((legacy_key.into_bytes(), balance.to_le_bytes().to_vec()));
            *total_supply = total_supply.saturating_add(balance);
            funded_count += 1;
        }
    }

    info!(
        "Installed ERC-8004 predeploys: {} contracts, {} storage slots, {} funded, source_commit={}",
        code_count, storage_slot_count, funded_count, bundle.source_commit
    );

    Ok(bundle_commitment)
}

/// Initialize genesis block and state
///
/// This function:
/// 1. Checks if genesis already exists (to support node restarts)
/// 2. Pre-funds configured genesis accounts
/// 3. Creates the genesis block at height 0
/// 4. Persists everything to RocksDB with fsync
pub async fn initialize_genesis(
    store: &Arc<RocksDbStore>,
    genesis_config: &GenesisConfig,
) -> Result<Block> {
    // Check if genesis already exists
    if genesis_exists(store)? {
        info!("Genesis block already exists, loading from storage");
        verify_chain_compat(store, genesis_config)?;
        return load_genesis_block(store).await;
    }

    info!(
        "Creating genesis block for chain_id={}",
        genesis_config.chain_id
    );

    // 1. Create account store and pre-fund accounts
    let mut account_store = AccountStoreImpl::new(store.clone());
    let mut state_entries: Vec<(Vec<u8>, Vec<u8>)> = Vec::new();
    // Token balance entries for CF_ACCOUNTS (used by TnzoToken RocksDbBackend)
    let mut token_entries: Vec<WriteOp> = Vec::new();
    let mut total_supply: u128 = 0;

    // Pre-fund genesis accounts
    for ga in &genesis_config.accounts {
        let address = parse_hex_address(&ga.address)?;
        // Multiply whole TNZO units by 10^18 to get smallest unit
        let balance_raw: u128 = ga.balance
            .checked_mul(1_000_000_000_000_000_000u128)
            .ok_or_else(|| {
                NodeError::Config(format!("Genesis balance overflow for {}", ga.address))
            })?;

        let account = Account {
            address,
            nonce: Nonce::initial(),
            balance: balance_raw,
            staked: 0,
            state: AccountState::default(),
            storage_root: Hash::zero(),
            code_hash: None,
        };

        account_store
            .put_account(&account)
            .await
            .map_err(|e| NodeError::Other(format!("Failed to store genesis account: {}", e)))?;

        // Store the full u128 balance in CF_STATE for the VM/token system
        let balance_key = format!("balance:{}", hex::encode(address.as_bytes()));
        state_entries.push((balance_key.into_bytes(), balance_raw.to_le_bytes().to_vec()));

        // Also store in CF_ACCOUNTS with TnzoToken-compatible key format (balance:{raw_bytes})
        let mut token_key = b"balance:".to_vec();
        token_key.extend_from_slice(address.as_bytes());
        token_entries.push(WriteOp::Put {
            cf: CF_ACCOUNTS.to_string(),
            key: token_key,
            value: balance_raw.to_le_bytes().to_vec(),
        });
        total_supply = total_supply.saturating_add(balance_raw);

        info!(
            "Pre-funded account {} with {} TNZO",
            ga.address, ga.balance
        );
    }

    // Pre-fund faucet account if configured
    if let Some(faucet) = &genesis_config.faucet
        && faucet.enabled
    {
            let address = parse_hex_address(&faucet.address)?;
            // Also persist the faucet address under CF_METADATA so later code
            // (e.g., the RPC faucet handler, the key provisioner) can look it
            // up without needing access to the genesis config file.
            store
                .put(
                    CF_METADATA,
                    b"genesis_faucet_address",
                    hex::encode(address.as_bytes()).as_bytes(),
                )
                .map_err(|e| NodeError::Other(format!("Failed to store genesis_faucet_address: {}", e)))?;
            let faucet_balance: u128 = 1_000_000_000 * 1_000_000_000_000_000_000u128; // 1B TNZO

            let account = Account {
                address,
                nonce: Nonce::initial(),
                balance: faucet_balance,
                staked: 0,
                state: AccountState::default(),
                storage_root: Hash::zero(),
                code_hash: None,
            };

            account_store
                .put_account(&account)
                .await
                .map_err(|e| NodeError::Other(format!("Failed to store faucet account: {}", e)))?;

            let balance_key = format!("balance:{}", hex::encode(address.as_bytes()));
            state_entries.push((
                balance_key.into_bytes(),
                faucet_balance.to_le_bytes().to_vec(),
            ));

            // Also store faucet balance in CF_ACCOUNTS for TnzoToken
            let mut token_key = b"balance:".to_vec();
            token_key.extend_from_slice(address.as_bytes());
            token_entries.push(WriteOp::Put {
                cf: CF_ACCOUNTS.to_string(),
                key: token_key,
                value: faucet_balance.to_le_bytes().to_vec(),
            });
            total_supply = total_supply.saturating_add(faucet_balance);

            info!(
                "Pre-funded faucet account with 1B TNZO (dispenses {} TNZO per request)",
                faucet.amount_per_request
            );
    }

    // Install ERC-8004 predeploys (factory + MinimalUUPS + 3 proxies + 3 impls).
    //
    // Must run before the CF_STATE flush so its entries get batched into the
    // same atomic write as the genesis-funded accounts. The returned
    // commitment binds the predeploy bundle into the genesis state root —
    // any drift in `erc8004-predeploys.json` produces a different root,
    // which any honest validator will reject on cross-check.
    let predeploys_commitment = install_erc8004_predeploys(
        &mut state_entries,
        &mut token_entries,
        &mut total_supply,
    )?;

    // Write state entries to CF_STATE
    if !state_entries.is_empty() {
        let ops: Vec<WriteOp> = state_entries
            .into_iter()
            .map(|(k, v)| WriteOp::Put {
                cf: CF_STATE.to_string(),
                key: k,
                value: v,
            })
            .collect();
        store
            .write_batch(ops)
            .map_err(|e| NodeError::Other(format!("Failed to write genesis state: {}", e)))?;
    }

    // Write token balances to CF_ACCOUNTS (used by TnzoToken::balance_of via RocksDbBackend)
    if !token_entries.is_empty() {
        // Also store total supply
        token_entries.push(WriteOp::Put {
            cf: CF_ACCOUNTS.to_string(),
            key: b"total_supply".to_vec(),
            value: total_supply.to_le_bytes().to_vec(),
        });
        store
            .write_batch(token_entries)
            .map_err(|e| NodeError::Other(format!("Failed to write genesis token balances: {}", e)))?;
        info!("Genesis token balances written to CF_ACCOUNTS (total supply: {} wei)", total_supply);
    }

    // 2. Compute state root (simplified - hash of all accounts + predeploy commitment)
    let state_root = compute_genesis_state_root(genesis_config, &predeploys_commitment);

    // 3. Create genesis block
    let timestamp = if genesis_config.timestamp > 0 {
        Timestamp::new(genesis_config.timestamp as i64 * 1000) // Convert seconds to milliseconds
    } else {
        Timestamp::now()
    };

    let genesis_block = Block {
        header: BlockHeader {
            height: BlockHeight::genesis(),
            view: 0,
            prev_hash: Hash::zero(),
            tx_root: Hash::zero(),
            state_root,
            timestamp,
            proposer: Address::zero(), // Genesis has no proposer
            consensus_proof: ConsensusProof::new(ConsensusAlgorithm::PoS, Vec::new()),
            metadata: BlockMetadata {
                gas_used: 0,
                gas_limit: 0,
                tx_count: 0,
                protocol_version: PQ_HYBRID_PROTOCOL_VERSION,
                // EIP-1559 base fee at genesis. Mirrors go-ethereum's
                // London-fork initial base fee (1 Gwei). Pre-launch
                // hard-codes the default; future genesis configs can
                // expose this as a field. The genesis-edge case in
                // `tenzro_types::block::calculate_next_base_fee` keys
                // off `gas_limit == 0` and returns this value, so the
                // child block at height 1 will stamp the same value.
                base_fee_per_gas: Some(
                    tenzro_types::block::FeeMarketParams::default().initial_base_fee,
                ),
            },
        },
        transactions: Vec::new(),
    };

    // 4. Persist genesis block
    let mut block_store = BlockStoreImpl::new(store.clone())
        .map_err(|e| NodeError::Other(format!("Failed to create block store: {}", e)))?;

    block_store
        .put_block(&genesis_block)
        .await
        .map_err(|e| NodeError::Other(format!("Failed to store genesis block: {}", e)))?;

    // 5. Mark genesis as initialized
    store
        .put(CF_METADATA, b"genesis_initialized", b"true")
        .map_err(|e| NodeError::Other(format!("Failed to mark genesis: {}", e)))?;

    // Store chain_id
    store
        .put(
            CF_METADATA,
            b"chain_id",
            &genesis_config.chain_id.to_le_bytes(),
        )
        .map_err(|e| NodeError::Other(format!("Failed to store chain_id: {}", e)))?;

    // Persist the genesis state_root so a restart-time chain-compat check
    // (`verify_chain_compat`) can refuse to start when the configured
    // genesis no longer matches the on-disk chain. Without this the only
    // way to detect "wrong genesis vs. existing DB" is by waiting for
    // consensus to diverge from peers — silent corruption of the
    // validator's local state until the operator notices. The state_root
    // already binds chain_id, accounts, faucet, and ERC-8004 predeploy
    // bundle (see `compute_genesis_state_root`), so a single 32-byte
    // value is sufficient to detect any genesis drift.
    store
        .put(
            CF_METADATA,
            b"genesis_state_root",
            state_root.as_bytes(),
        )
        .map_err(|e| NodeError::Other(format!("Failed to store genesis_state_root: {}", e)))?;

    info!(
        "Genesis block created at height 0, state_root={}",
        state_root
    );

    Ok(genesis_block)
}

/// Compute the SHA-256 commitment of the embedded ERC-8004 predeploy bundle.
///
/// The same commitment is folded into the genesis state_root (so validators
/// must agree on the exact predeploy set) and is referenced by
/// `verify_chain_compat` to detect binary-level genesis drift on restart.
fn compute_erc8004_bundle_commitment() -> Hash {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(b"tenzro/erc8004-predeploys");
    h.update(ERC8004_PREDEPLOYS_JSON.as_bytes());
    let digest = h.finalize();
    Hash::from_bytes(digest.as_slice())
        .expect("SHA-256 always produces 32 bytes")
}

/// Cross-check the configured genesis against what's already persisted on
/// disk. Refuse to start on any drift in chain_id or genesis state_root.
///
/// This is the safety check that lets validators preserve
/// their RocksDB across binary upgrades without risking silent state
/// corruption. The decision tree is:
///
/// - **Same chain (chain_id + state_root both match)**: log a debug line
///   and continue — the on-disk chain is the right one.
/// - **chain_id drift**: hard error. The operator pointed the binary at
///   the wrong genesis file or a different network's data directory.
///   Refusing to start is the safe action; silently continuing would
///   give the binary one chain's transactions over another chain's
///   state. The operator must either fix the genesis path or
///   intentionally wipe the data directory.
/// - **state_root drift on the same chain_id**: also a hard error.
///   Either the genesis file was edited (different accounts, faucet, or
///   predeploy bundle) or the binary itself carries a new predeploy
///   commitment. Both demand operator action — there is no safe
///   automatic recovery.
/// - **No `genesis_state_root` key persisted**: only possible on a pre-fix
///   upgrade path. Back-fill the key from the configured genesis and
///   accept the chain as-is. The on-disk genesis block's state_root will
///   be cross-checked at `load_genesis_block` time anyway, so this
///   back-fill is safe.
///
/// Errors are surfaced as `NodeError::Config` so the operator gets a
/// clean abort with an actionable message rather than a panic.
fn verify_chain_compat(
    store: &Arc<RocksDbStore>,
    genesis_config: &GenesisConfig,
) -> Result<()> {
    // 1. chain_id check
    let stored_chain_id_bytes = store
        .get(CF_METADATA, b"chain_id")
        .map_err(|e| NodeError::Other(format!("Failed to read stored chain_id: {}", e)))?;
    if let Some(bytes) = stored_chain_id_bytes {
        if bytes.len() != 8 {
            return Err(NodeError::Other(format!(
                "Stored chain_id has wrong length: expected 8 bytes (u64 LE), got {}. \
                 Storage may be corrupt — investigate before retrying.",
                bytes.len()
            )));
        }
        let mut chain_id_arr = [0u8; 8];
        chain_id_arr.copy_from_slice(&bytes);
        let stored_chain_id = u64::from_le_bytes(chain_id_arr);
        if stored_chain_id != genesis_config.chain_id {
            return Err(NodeError::Config(format!(
                "Chain incompatibility detected: configured genesis chain_id={} but \
                 on-disk chain has chain_id={}. This binary will not start against \
                 a foreign chain's state. Either (a) point --genesis at the correct \
                 genesis.toml for chain_id={}, or (b) intentionally wipe the data \
                 directory (rm -rf <data-dir>/db <data-dir>/snapshots \
                 <data-dir>/consensus) to bootstrap a fresh chain.",
                genesis_config.chain_id, stored_chain_id, stored_chain_id
            )));
        }
    } else {
        // chain_id missing while genesis_initialized is true — back-fill so
        // future checks have something to compare against. Storage is from
        // a pre-fix binary; the on-disk chain is whatever the binary
        // assumes. We accept it; the state_root check below will still
        // catch drift in the binary's genesis assembly.
        store
            .put(
                CF_METADATA,
                b"chain_id",
                &genesis_config.chain_id.to_le_bytes(),
            )
            .map_err(|e| NodeError::Other(format!("Failed to back-fill chain_id: {}", e)))?;
        info!(
            "Back-filled chain_id={} into CF_METADATA (pre-fix upgrade path)",
            genesis_config.chain_id
        );
    }

    // 2. genesis_state_root check
    let predeploys_commitment = compute_erc8004_bundle_commitment();
    let configured_root = compute_genesis_state_root(genesis_config, &predeploys_commitment);

    let stored_root_bytes = store
        .get(CF_METADATA, b"genesis_state_root")
        .map_err(|e| NodeError::Other(format!("Failed to read stored genesis_state_root: {}", e)))?;
    if let Some(bytes) = stored_root_bytes {
        if bytes.len() != 32 {
            return Err(NodeError::Other(format!(
                "Stored genesis_state_root has wrong length: expected 32 bytes, got {}. \
                 Storage may be corrupt — investigate before retrying.",
                bytes.len()
            )));
        }
        let mut stored_arr = [0u8; 32];
        stored_arr.copy_from_slice(&bytes);
        let stored_root = Hash::from_bytes(&stored_arr)
            .expect("32-byte slice always converts to Hash");
        if stored_root != configured_root {
            return Err(NodeError::Config(format!(
                "Genesis state_root mismatch: configured genesis hashes to {} but \
                 on-disk genesis was {}. Either the genesis.toml was edited (different \
                 accounts, faucet, validators, or ERC-8004 predeploy bundle), or this \
                 binary carries a different predeploy bundle than the one used to \
                 bootstrap the on-disk chain. Refusing to start to prevent silent \
                 state corruption. Resolve by (a) reverting the genesis change, or \
                 (b) intentionally wiping the data directory to bootstrap a fresh chain.",
                configured_root, stored_root
            )));
        }
        info!(
            "Chain compatibility verified: chain_id={} genesis_state_root={}",
            genesis_config.chain_id, configured_root
        );
    } else {
        // genesis_state_root missing — back-fill, same reasoning as chain_id.
        store
            .put(
                CF_METADATA,
                b"genesis_state_root",
                configured_root.as_bytes(),
            )
            .map_err(|e| NodeError::Other(format!("Failed to back-fill genesis_state_root: {}", e)))?;
        info!(
            "Back-filled genesis_state_root={} into CF_METADATA (pre-fix upgrade path)",
            configured_root
        );
    }

    Ok(())
}

/// Check if genesis block has already been initialized
fn genesis_exists(store: &Arc<RocksDbStore>) -> Result<bool> {
    match store.get(CF_METADATA, b"genesis_initialized") {
        Ok(Some(_)) => Ok(true),
        Ok(None) => Ok(false),
        Err(e) => Err(NodeError::Other(format!(
            "Failed to check genesis: {}",
            e
        ))),
    }
}

/// Load existing genesis block from storage
async fn load_genesis_block(store: &Arc<RocksDbStore>) -> Result<Block> {
    let block_store = BlockStoreImpl::new(store.clone())
        .map_err(|e| NodeError::Other(format!("Failed to create block store: {}", e)))?;

    let genesis = block_store
        .get_block_by_height(BlockHeight::genesis())
        .await
        .map_err(|e| NodeError::Other(format!("Failed to load genesis block: {}", e)))?
        .ok_or_else(|| NodeError::Other("Genesis block not found in storage".to_string()))?;

    // Refuse to start on a pre-PQ genesis. The classical-only wire format from
    // protocol_version=1 is not deserializable by this binary; bringing it up
    // would silently accept a chain whose transaction format we cannot replay.
    let stored_version = genesis.header.metadata.protocol_version;
    if stored_version < PQ_HYBRID_PROTOCOL_VERSION {
        return Err(NodeError::Other(format!(
            "Refusing to start: stored genesis declares protocol_version={} but \
             this binary requires protocol_version={} (PQ-hybrid era). The older \
             classical-only transaction format is no longer supported. Wipe the \
             data directory to re-bootstrap from genesis.",
            stored_version, PQ_HYBRID_PROTOCOL_VERSION
        )));
    }

    info!(
        "Loaded existing genesis block from storage (protocol_version={})",
        stored_version
    );
    Ok(genesis)
}

/// Parse hex-encoded address (with or without 0x prefix)
fn parse_hex_address(hex_str: &str) -> Result<Address> {
    let hex_clean = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    let bytes = hex::decode(hex_clean).map_err(|e| {
        NodeError::Config(format!("Invalid hex address '{}': {}", hex_str, e))
    })?;

    if bytes.len() > 32 {
        return Err(NodeError::Config(format!(
            "Address too long: {} bytes (max 32)",
            bytes.len()
        )));
    }

    let mut addr_bytes = [0u8; 32];
    let len = bytes.len().min(32);
    addr_bytes[..len].copy_from_slice(&bytes[..len]);

    Ok(Address::new(addr_bytes))
}

/// Compute the genesis state root from the configuration.
///
/// The genesis root is a deterministic SHA-256 commitment over the genesis
/// configuration (chain id, funded accounts, faucet parameters) plus the
/// ERC-8004 predeploy bundle commitment — intentionally NOT a Merkle
/// Patricia Trie root. Genesis state is injected into the state trie
/// separately at boot; this value only needs to be identical across every
/// validator loading the same configuration, and it is baked into the live
/// genesis, so its preimage layout must never change. Binding
/// `predeploys_commitment` here means any drift in
/// `erc8004-predeploys.json` (bytecode, slot values, the set of addresses)
/// produces a different genesis root, so a peer with a stale bundle will
/// fail header verification.
fn compute_genesis_state_root(genesis: &GenesisConfig, predeploys_commitment: &Hash) -> Hash {
    use sha2::{Digest, Sha256};

    let mut hasher = Sha256::new();
    hasher.update(b"tenzro_genesis_v1");
    hasher.update(genesis.chain_id.to_le_bytes());

    // Hash all genesis accounts
    for account in &genesis.accounts {
        hasher.update(account.address.as_bytes());
        hasher.update(account.balance.to_le_bytes());
    }

    // Hash faucet if enabled
    if let Some(faucet) = &genesis.faucet
        && faucet.enabled
    {
        hasher.update(faucet.address.as_bytes());
        hasher.update(1_000_000_000u64.to_le_bytes()); // 1B TNZO total balance
        hasher.update(faucet.amount_per_request.to_le_bytes());
        hasher.update(faucet.cooldown_seconds.to_le_bytes());
    }

    // Bind ERC-8004 predeploy bundle into the root.
    hasher.update(predeploys_commitment.as_bytes());

    let result = hasher.finalize();
    Hash::from_bytes(result.as_slice())
        .expect("SHA-256 always produces 32 bytes")
}

/// Provision a real Ed25519 signing keypair for the faucet, if one doesn't
/// already exist.
///
/// The original testnet genesis funded a sentinel address (`0x0000...ffffff`)
/// with 1B TNZO, but no private key backed that address — so the faucet RPC
/// handler was forced to call `token.transfer()` directly, bypassing consensus
/// entirely. That left state divergent across validators and made
/// `tenzro_getTransaction` always return null for faucet-dispensed tx hashes.
///
/// This function fixes that by:
///
/// 1. Checking if `FAUCET_SIGNING_KEY_PRIVATE` already exists in CF_METADATA.
///    If so, returns early — idempotent on reboot.
/// 2. Generating a fresh Ed25519 keypair.
/// 3. Deriving a 32-byte Tenzro address from the public key (pubkey bytes ARE
///    the address, matching how `tenzro_participate` provisions user
///    addresses).
/// 4. Transferring any remaining balance from the legacy sentinel faucet
///    address (as recorded under `genesis_faucet_address`) to the new
///    keypair-backed address, by directly rewriting the CF_ACCOUNTS balance
///    entries. This is a one-time bootstrap migration — all subsequent faucet
///    dispenses go through consensus.
/// 5. Persisting the privkey, pubkey, and new address under CF_METADATA. Also
///    overwrites `genesis_faucet_address` so any existing code that reads it
///    sees the new signing address.
///
/// Callers: invoked once at node startup, immediately after
/// `initialize_genesis()`.
pub async fn provision_faucet_signing_key(store: &Arc<RocksDbStore>) -> Result<()> {
    // Idempotent check: if a privkey is already persisted, ensure the
    // ML-DSA-65 leg is also present and back-fill it if not. This handles
    // upgrades from a classical-only node that only persisted the Ed25519 key.
    if let Ok(Some(_)) = store.get(CF_METADATA, FAUCET_SIGNING_KEY_PRIVATE) {
        if matches!(store.get(CF_METADATA, FAUCET_PQ_SIGNING_SEED), Ok(Some(_))) {
            info!("Faucet signing key already provisioned, skipping");
            return Ok(());
        }
        info!("Back-filling faucet PQ signing key (hybrid PQ migration)");
        let pq_key = tenzro_crypto::pq::MlDsaSigningKey::generate();
        let pq_seed_hex = hex::encode(pq_key.seed_bytes());
        let pq_vk_hex = hex::encode(pq_key.verifying_key_bytes());
        let ops = vec![
            WriteOp::Put {
                cf: CF_METADATA.to_string(),
                key: FAUCET_PQ_SIGNING_SEED.to_vec(),
                value: pq_seed_hex.into_bytes(),
            },
            WriteOp::Put {
                cf: CF_METADATA.to_string(),
                key: FAUCET_PQ_VERIFYING_KEY.to_vec(),
                value: pq_vk_hex.into_bytes(),
            },
        ];
        store.write_batch(ops).map_err(|e| {
            NodeError::Other(format!("Failed to back-fill faucet PQ key: {}", e))
        })?;
        return Ok(());
    }

    info!("Provisioning faucet signing key (one-time bootstrap)");

    // Generate a fresh Ed25519 keypair for the faucet.
    let keypair = KeyPair::generate(KeyType::Ed25519).map_err(|e| {
        NodeError::Other(format!("Failed to generate faucet keypair: {}", e))
    })?;
    let pubkey_bytes = keypair.public_key().as_bytes().to_vec();
    let privkey_bytes = keypair.secret_key().as_bytes().to_vec();

    // Derive the 32-byte Tenzro address from the public key. In this codebase,
    // `tenzro_types::Address` is 32 bytes, and Ed25519 public keys are also
    // 32 bytes, so the address IS the pubkey when cast to `Address`.
    if pubkey_bytes.len() != 32 {
        return Err(NodeError::Other(format!(
            "Unexpected Ed25519 public key length: got {}, expected 32",
            pubkey_bytes.len()
        )));
    }
    let new_faucet_address = Address::from_bytes(&pubkey_bytes)
        .ok_or_else(|| NodeError::Other("Failed to build faucet address from pubkey".to_string()))?;

    // Load the legacy sentinel faucet address (if any) so we can migrate its
    // remaining balance to the new signing address.
    let legacy_addr_opt: Option<Address> = match store.get(CF_METADATA, b"genesis_faucet_address") {
        Ok(Some(bytes)) => {
            let hex_str = String::from_utf8(bytes).ok();
            hex_str.and_then(|h| Address::from_hex(&h).ok())
        }
        _ => None,
    };

    // Migrate legacy sentinel balance → new signing address.
    if let Some(legacy_addr) = legacy_addr_opt {
        migrate_faucet_balance(store, &legacy_addr, &new_faucet_address)?;
    } else {
        warn!(
            "No legacy faucet address found under metadata; new faucet will \
             start with zero balance until explicitly funded"
        );
    }

    // Provision the faucet's PQ signing identity (hybrid migration).
    // The seed is the deterministic source of truth — the verifying key is
    // rederived from it on every load.
    let pq_key = tenzro_crypto::pq::MlDsaSigningKey::generate();
    let pq_seed_hex = hex::encode(pq_key.seed_bytes());
    let pq_vk_hex = hex::encode(pq_key.verifying_key_bytes());

    // Persist keypair + new address under CF_METADATA. We store hex-encoded
    // strings so ops/debugging is straightforward.
    let privkey_hex = hex::encode(&privkey_bytes);
    let pubkey_hex = hex::encode(&pubkey_bytes);
    let address_hex = hex::encode(new_faucet_address.as_bytes());

    let ops = vec![
        WriteOp::Put {
            cf: CF_METADATA.to_string(),
            key: FAUCET_SIGNING_KEY_PRIVATE.to_vec(),
            value: privkey_hex.into_bytes(),
        },
        WriteOp::Put {
            cf: CF_METADATA.to_string(),
            key: FAUCET_SIGNING_KEY_PUBLIC.to_vec(),
            value: pubkey_hex.into_bytes(),
        },
        WriteOp::Put {
            cf: CF_METADATA.to_string(),
            key: FAUCET_SIGNING_KEY_ADDRESS.to_vec(),
            value: address_hex.clone().into_bytes(),
        },
        WriteOp::Put {
            cf: CF_METADATA.to_string(),
            key: FAUCET_PQ_SIGNING_SEED.to_vec(),
            value: pq_seed_hex.into_bytes(),
        },
        WriteOp::Put {
            cf: CF_METADATA.to_string(),
            key: FAUCET_PQ_VERIFYING_KEY.to_vec(),
            value: pq_vk_hex.into_bytes(),
        },
        // Overwrite the legacy genesis_faucet_address pointer so any code
        // reading it picks up the new signing address transparently.
        WriteOp::Put {
            cf: CF_METADATA.to_string(),
            key: b"genesis_faucet_address".to_vec(),
            value: address_hex.into_bytes(),
        },
    ];

    store
        .write_batch(ops)
        .map_err(|e| NodeError::Other(format!("Failed to persist faucet signing key: {}", e)))?;

    info!(
        "Faucet signing key provisioned; new faucet address = 0x{}",
        hex::encode(new_faucet_address.as_bytes())
    );

    Ok(())
}

/// Refill the faucet to its target balance if it has run dry.
///
/// The faucet account funds itself once at first boot via
/// `provision_faucet_signing_key()` (which migrates the 1B TNZO genesis
/// allocation from the legacy sentinel address). However, sustained
/// dispensing — or, in pre-alpha, a state divergence from a chain restart —
/// can leave the faucet at zero balance. Without a refill mechanism, the
/// faucet stays broken until a full chain wipe.
///
/// This function runs on every node boot, after `provision_faucet_signing_key`,
/// and tops up the faucet to `FAUCET_TARGET_BALANCE_TNZO` (10M TNZO) if its
/// current balance is below `FAUCET_REFILL_THRESHOLD_TNZO` (1M TNZO). Funds
/// are minted into the faucet's CF_ACCOUNTS row directly — same mechanism as
/// the original genesis allocation. Total supply increments accordingly.
///
/// Idempotent: a no-op when balance is above threshold.
pub async fn refill_faucet_if_low(store: &Arc<RocksDbStore>) -> Result<()> {
    const FAUCET_REFILL_THRESHOLD_WEI: u128 = 1_000_000 * 1_000_000_000_000_000_000u128; // 1M TNZO
    const FAUCET_TARGET_BALANCE_WEI: u128 = 10_000_000 * 1_000_000_000_000_000_000u128;  // 10M TNZO

    let address_hex = match store.get(CF_METADATA, FAUCET_SIGNING_KEY_ADDRESS) {
        Ok(Some(bytes)) => match String::from_utf8(bytes) {
            Ok(s) => s,
            Err(_) => {
                warn!("Faucet refill skipped: address is not valid UTF-8 hex");
                return Ok(());
            }
        },
        _ => {
            // Faucet not yet provisioned — refill happens on the next boot.
            return Ok(());
        }
    };

    let faucet_addr = match Address::from_hex(&address_hex) {
        Ok(a) => a,
        Err(e) => {
            warn!("Faucet refill skipped: invalid persisted address: {}", e);
            return Ok(());
        }
    };

    let mut balance_key = b"balance:".to_vec();
    balance_key.extend_from_slice(faucet_addr.as_bytes());

    let current_balance: u128 = match store.get(CF_ACCOUNTS, &balance_key) {
        Ok(Some(bytes)) if bytes.len() == 16 => {
            let arr: [u8; 16] = bytes.try_into().unwrap();
            u128::from_le_bytes(arr)
        }
        _ => 0,
    };

    if current_balance >= FAUCET_REFILL_THRESHOLD_WEI {
        info!(
            "Faucet balance is {} wei (>= {} wei threshold); skipping refill",
            current_balance, FAUCET_REFILL_THRESHOLD_WEI
        );
        return Ok(());
    }

    let topup = FAUCET_TARGET_BALANCE_WEI.saturating_sub(current_balance);
    let new_balance = FAUCET_TARGET_BALANCE_WEI;

    let ops = vec![WriteOp::Put {
        cf: CF_ACCOUNTS.to_string(),
        key: balance_key,
        value: new_balance.to_le_bytes().to_vec(),
    }];

    store
        .write_batch(ops)
        .map_err(|e| NodeError::Other(format!("Failed to refill faucet: {}", e)))?;

    info!(
        "Faucet refilled: address=0x{} previous_balance={} top_up={} new_balance={}",
        hex::encode(faucet_addr.as_bytes()),
        current_balance,
        topup,
        new_balance
    );

    Ok(())
}

/// Move the faucet balance from the legacy sentinel address to the new
/// keypair-backed signing address. Directly rewrites CF_ACCOUNTS balance
/// entries.
///
/// Idempotency: if the legacy address is already empty, this is a no-op.
/// If the destination already has a balance (e.g., from a partial previous
/// migration), amounts are summed so we don't lose funds.
fn migrate_faucet_balance(
    store: &Arc<RocksDbStore>,
    legacy: &Address,
    new: &Address,
) -> Result<()> {
    // Keys match the TnzoToken RocksDbBackend layout: "balance:" + address bytes
    let mut legacy_key = b"balance:".to_vec();
    legacy_key.extend_from_slice(legacy.as_bytes());
    let mut new_key = b"balance:".to_vec();
    new_key.extend_from_slice(new.as_bytes());

    let legacy_balance: u128 = match store.get(CF_ACCOUNTS, &legacy_key) {
        Ok(Some(bytes)) if bytes.len() == 16 => {
            let arr: [u8; 16] = bytes.try_into().unwrap();
            u128::from_le_bytes(arr)
        }
        _ => 0,
    };

    if legacy_balance == 0 {
        info!("Legacy faucet address has zero balance; nothing to migrate");
        return Ok(());
    }

    let existing_new_balance: u128 = match store.get(CF_ACCOUNTS, &new_key) {
        Ok(Some(bytes)) if bytes.len() == 16 => {
            let arr: [u8; 16] = bytes.try_into().unwrap();
            u128::from_le_bytes(arr)
        }
        _ => 0,
    };

    let merged = existing_new_balance
        .checked_add(legacy_balance)
        .ok_or_else(|| NodeError::Other("Faucet balance migration overflow".to_string()))?;

    let ops = vec![
        WriteOp::Put {
            cf: CF_ACCOUNTS.to_string(),
            key: new_key,
            value: merged.to_le_bytes().to_vec(),
        },
        WriteOp::Put {
            cf: CF_ACCOUNTS.to_string(),
            key: legacy_key,
            value: 0u128.to_le_bytes().to_vec(),
        },
    ];

    store
        .write_batch(ops)
        .map_err(|e| NodeError::Other(format!("Failed to migrate faucet balance: {}", e)))?;

    info!(
        "Migrated faucet balance: {} wei moved from legacy address 0x{} to new address 0x{}",
        legacy_balance,
        hex::encode(legacy.as_bytes()),
        hex::encode(new.as_bytes())
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tenzro_storage::StorageConfig;

    #[test]
    fn faucet_grant_is_clamped_to_the_permitted_range() {
        assert_eq!(resolve_faucet_grant_tnzo(500), 500);
        assert_eq!(resolve_faucet_grant_tnzo(1), FAUCET_MIN_GRANT_TNZO);
        assert_eq!(resolve_faucet_grant_tnzo(10_000), FAUCET_MAX_GRANT_TNZO);
    }

    #[tokio::test]
    async fn test_genesis_creation() {
        let temp_dir = tempfile::tempdir().unwrap();
        let storage_config = StorageConfig::new(temp_dir.path().to_path_buf());
        let store = Arc::new(RocksDbStore::open(&storage_config).unwrap());

        let genesis_config = GenesisConfig {
            version: crate::config::MIN_GENESIS_VERSION,
            chain_id: 1337,
            timestamp: 0,
            validators: vec![],
            accounts: vec![crate::config::GenesisAccount {
                address: "0x1111111111111111111111111111111111111111".to_string(),
                balance: 10, // 10 TNZO (whole units, multiplied by 10^18 in genesis init)
            }],
            faucet: None,
            weak_subjectivity: None,
        };

        // First initialization should create genesis
        let block1 = initialize_genesis(&store, &genesis_config).await.unwrap();
        assert_eq!(block1.height(), BlockHeight::genesis());
        assert_eq!(block1.transactions.len(), 0);

        // Second initialization should load existing genesis
        let block2 = initialize_genesis(&store, &genesis_config).await.unwrap();
        assert_eq!(block1.hash(), block2.hash());

        // Verify chain_id was stored
        let chain_id_bytes = store.get(CF_METADATA, b"chain_id").unwrap().unwrap();
        let chain_id = u64::from_le_bytes(chain_id_bytes.try_into().unwrap());
        assert_eq!(chain_id, 1337);
    }

    #[tokio::test]
    async fn test_genesis_with_faucet() {
        let temp_dir = tempfile::tempdir().unwrap();
        let storage_config = StorageConfig::new(temp_dir.path().to_path_buf());
        let store = Arc::new(RocksDbStore::open(&storage_config).unwrap());

        let genesis_config = GenesisConfig {
            version: crate::config::MIN_GENESIS_VERSION,
            chain_id: 1337,
            timestamp: 0,
            validators: vec![],
            accounts: vec![],
            faucet: Some(crate::config::FaucetConfig {
                address: "0x2222222222222222222222222222222222222222".to_string(),
                amount_per_request: 100,
                cooldown_seconds: 86400,
                enabled: true,
            }),
            weak_subjectivity: None,
        };

        let block = initialize_genesis(&store, &genesis_config).await.unwrap();
        assert_eq!(block.height(), BlockHeight::genesis());

        // Verify faucet account was created
        let account_store = AccountStoreImpl::new(store.clone());
        let faucet_addr = parse_hex_address("0x2222222222222222222222222222222222222222").unwrap();
        let account = account_store.get_account(&faucet_addr).await.unwrap();
        assert!(account.is_some());
    }

    #[test]
    fn test_parse_hex_address() {
        // With 0x prefix
        let addr1 = parse_hex_address("0x1234567890abcdef1234567890abcdef12345678").unwrap();
        assert_eq!(&addr1.as_bytes()[..20], &hex::decode("1234567890abcdef1234567890abcdef12345678").unwrap()[..]);

        // Without 0x prefix
        let addr2 = parse_hex_address("1234567890abcdef1234567890abcdef12345678").unwrap();
        assert_eq!(&addr2.as_bytes()[..20], &hex::decode("1234567890abcdef1234567890abcdef12345678").unwrap()[..]);

        // Invalid hex
        assert!(parse_hex_address("0xZZZZ").is_err());
    }

    #[test]
    fn test_compute_state_root() {
        let config1 = GenesisConfig {
            version: crate::config::MIN_GENESIS_VERSION,
            chain_id: 1337,
            timestamp: 0,
            validators: vec![],
            accounts: vec![crate::config::GenesisAccount {
                address: "0x1111111111111111111111111111111111111111".to_string(),
                balance: 1000,
            }],
            faucet: None,
            weak_subjectivity: None,
        };

        let config2 = GenesisConfig {
            version: crate::config::MIN_GENESIS_VERSION,
            chain_id: 1337,
            timestamp: 0,
            validators: vec![],
            accounts: vec![crate::config::GenesisAccount {
                address: "0x1111111111111111111111111111111111111111".to_string(),
                balance: 2000, // Different balance
            }],
            faucet: None,
            weak_subjectivity: None,
        };

        // Use a fixed dummy predeploy commitment for both — the test is
        // about the config inputs differing, not the predeploy bundle.
        let dummy_commitment = Hash::zero();
        let root1 = compute_genesis_state_root(&config1, &dummy_commitment);
        let root2 = compute_genesis_state_root(&config2, &dummy_commitment);

        // Different configurations should produce different state roots
        assert_ne!(root1, root2);
    }

    fn chain_compat_genesis(chain_id: u64, balance: u128) -> GenesisConfig {
        GenesisConfig {
            version: crate::config::MIN_GENESIS_VERSION,
            chain_id,
            timestamp: 0,
            validators: vec![],
            accounts: vec![crate::config::GenesisAccount {
                address: "0x1111111111111111111111111111111111111111".to_string(),
                balance,
            }],
            faucet: None,
            weak_subjectivity: None,
        }
    }

    #[tokio::test]
    async fn verify_chain_compat_succeeds_on_identical_genesis() {
        let temp_dir = tempfile::tempdir().unwrap();
        let storage_config = StorageConfig::new(temp_dir.path().to_path_buf());
        let store = Arc::new(RocksDbStore::open(&storage_config).unwrap());

        let cfg = chain_compat_genesis(7777, 100);

        // First initialization writes chain_id + genesis_state_root.
        initialize_genesis(&store, &cfg).await.unwrap();

        // Second call hits the existing-genesis path → runs verify_chain_compat.
        // Identical config must not error.
        initialize_genesis(&store, &cfg).await.unwrap();
    }

    #[tokio::test]
    async fn verify_chain_compat_rejects_chain_id_mismatch() {
        let temp_dir = tempfile::tempdir().unwrap();
        let storage_config = StorageConfig::new(temp_dir.path().to_path_buf());
        let store = Arc::new(RocksDbStore::open(&storage_config).unwrap());

        let cfg_a = chain_compat_genesis(7777, 100);
        initialize_genesis(&store, &cfg_a).await.unwrap();

        // Point at a different chain_id — must refuse.
        let cfg_b = chain_compat_genesis(8888, 100);
        let err = initialize_genesis(&store, &cfg_b).await.unwrap_err();
        let msg = format!("{}", err);
        assert!(
            msg.contains("chain_id=7777") && msg.contains("chain_id=8888"),
            "expected chain_id mismatch message, got: {}",
            msg
        );
    }

    #[tokio::test]
    async fn verify_chain_compat_rejects_state_root_mismatch() {
        let temp_dir = tempfile::tempdir().unwrap();
        let storage_config = StorageConfig::new(temp_dir.path().to_path_buf());
        let store = Arc::new(RocksDbStore::open(&storage_config).unwrap());

        let cfg_a = chain_compat_genesis(7777, 100);
        initialize_genesis(&store, &cfg_a).await.unwrap();

        // Same chain_id, different genesis content (different account balance).
        // state_root must differ → verify_chain_compat refuses.
        let cfg_b = chain_compat_genesis(7777, 200);
        let err = initialize_genesis(&store, &cfg_b).await.unwrap_err();
        let msg = format!("{}", err);
        assert!(
            msg.contains("Genesis state_root mismatch"),
            "expected state_root mismatch message, got: {}",
            msg
        );
    }

    #[tokio::test]
    async fn verify_chain_compat_backfills_when_keys_missing() {
        // Simulate the pre-fix upgrade path: a chain was initialised by an
        // older binary that didn't write `genesis_state_root` (and possibly
        // not `chain_id` either). Deleting both keys after init, then
        // re-running, should back-fill them and accept the chain instead
        // of refusing to start.
        let temp_dir = tempfile::tempdir().unwrap();
        let storage_config = StorageConfig::new(temp_dir.path().to_path_buf());
        let store = Arc::new(RocksDbStore::open(&storage_config).unwrap());

        let cfg = chain_compat_genesis(7777, 100);
        initialize_genesis(&store, &cfg).await.unwrap();

        // Wipe the two keys to simulate pre-fix state.
        store.delete(CF_METADATA, b"chain_id").unwrap();
        store.delete(CF_METADATA, b"genesis_state_root").unwrap();

        // Must succeed and back-fill.
        initialize_genesis(&store, &cfg).await.unwrap();

        let stored_chain_id_bytes = store
            .get(CF_METADATA, b"chain_id")
            .unwrap()
            .expect("chain_id should be back-filled");
        assert_eq!(stored_chain_id_bytes.len(), 8);

        let stored_root_bytes = store
            .get(CF_METADATA, b"genesis_state_root")
            .unwrap()
            .expect("genesis_state_root should be back-filled");
        assert_eq!(stored_root_bytes.len(), 32);
    }
}
