//! TDIP ↔ iroh identity bridge — Phase C2 (#220).
//!
//! The iroh transport identifies endpoints by a 32-byte Ed25519 public key
//! (`iroh_base::EndpointId` is `[u8; 32]`). A Tenzro node has a 32-byte
//! Ed25519 identity seed (the validator/identity key generated by `tenzro-node
//! init` and persisted under `{data_dir}/keys/`). Both halves are the
//! same curve and the same key material.
//!
//! [`derive_iroh_secret_key_from_ed25519`] is a thin, well-typed conversion
//! that documents this equivalence at the seam — when a node binds its iroh
//! endpoint, the resulting `EndpointId` is byte-identical to the node's
//! TDIP public key. Pkarr records signed by this key therefore bind the
//! discovered iroh address to the on-chain DID without any extra
//! attestation layer.
//!
//! The TDIP-anchored Pkarr relay (operator-deployed at e.g.
//! `https://pkarr.tenzro.xyz/pkarr`) accepts `SignedPacket`s whose
//! signing key was issued by Tenzro's identity registry. The relay's
//! admission policy lives in the relay deployment (not in this crate); on
//! the client side the contribution is to *use the right key* so the relay
//! can verify the binding.

use iroh_base::SecretKey;

/// Derive an iroh `SecretKey` from a 32-byte Ed25519 seed.
///
/// Both `iroh_base::SecretKey` and the node's TDIP identity key are
/// Ed25519 over the same curve; the conversion is a direct passthrough of
/// the 32-byte seed material. Use the same seed the node uses for its
/// validator/identity key so the iroh `EndpointId` matches the node DID's
/// public key.
pub fn derive_iroh_secret_key_from_ed25519(seed: &[u8; 32]) -> SecretKey {
    SecretKey::from_bytes(seed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn derived_secret_key_is_deterministic() {
        let seed = [42u8; 32];
        let a = derive_iroh_secret_key_from_ed25519(&seed);
        let b = derive_iroh_secret_key_from_ed25519(&seed);
        assert_eq!(a.public(), b.public());
    }

    #[test]
    fn different_seeds_yield_different_endpoint_ids() {
        let a = derive_iroh_secret_key_from_ed25519(&[1u8; 32]);
        let b = derive_iroh_secret_key_from_ed25519(&[2u8; 32]);
        assert_ne!(a.public(), b.public());
    }
}
